feat: faculty profile page
nitkkr-dev/nitkkr pull request #110
Opened 2024-03-21 12:53 UTC by SilentJungle399

2024-03-21 13:35 UTC, GetPsyched requested changes

2024-03-21 13:35 UTC, GetPsyched commented on app/[locale]/faculty-and-staff/[id]/page.tsx
> +'use client';
Don't make this entire file client-side. Abstract out the currentTab functionality to another file as a component and then import that.

2024-03-21 13:35 UTC, GetPsyched commented on app/[locale]/faculty-and-staff/[id]/page.tsx
> +      },
These things are dynamic, don't make an object that has both static and dynamic data. See the following fields we have in the faculty table and mimic that here.
https://github.com/nitkkr-dev/nitkkr/blob/46d2cebea9a8464cbc9a0a32f8b1fe83ba1ea176/server/db/faculty.ts#L14-L43

2025-05-02 09:03 UTC, heydoyouknowme0 commented
outdated

2025-05-02 09:03 UTC, closed without merging