Feature/forms drizzle
nitkkr-dev/nitkkr pull request #112
Opened 2024-03-29 06:30 UTC by heydoyouknowme0

2024-03-29 20:39 UTC, GetPsyched reviewed
This doesn't build?

2024-03-29 22:24 UTC, heydoyouknowme0 commented
Locally it does build

2024-03-30 06:19 UTC, GetPsyched requested changes

2024-03-30 06:19 UTC, GetPsyched commented on components/forms/schemas/form.ts
This file isn't being used anywhere as it exists also as `schemas/forms.ts`

Moreover, do we really need this?

2024-03-30 07:07 UTC, heydoyouknowme0 commented on components/forms/schemas/form.ts
its being used by both backend and frontend validation, I meant to cut it inside forms a it's better considering the scope duplicated accidentally across commits

2024-06-08 13:19 UTC, GetPsyched commented
Split into:
- #197 
- #132
- #187
- #186

2024-06-08 13:19 UTC, closed without merging