feat: clubs
nitkkr-dev/nitkkr pull request #204
Opened 2024-06-21 03:28 UTC by KambojRajan

2024-06-28 18:42 UTC, geekysilento requested changes
![image](https://github.com/nitkkr-dev/nitkkr/assets/125768789/4417bcd3-b42f-41e7-a9bd-332db07a13aa)
- The image bleeds out of its div
- The Heading of the club page is h1, so are all the subheadings, please make subheadings smaller.

2024-07-11 18:19 UTC, GetPsyched requested changes
is this still a work in progress? I only see About and RSVP heading. The design has a lot more stuff.

Also what is RSVP here?

2024-07-12 01:40 UTC, KambojRajan commented
We have a design for this? Additionally, there is little to no data available for many of the clubs(in the current website). For clubs that have complete data, the components will display properly. for me this is not wip. The RSVP section will include the names and contact information of either the students in the club or the secretary if you want to name it some other way I will do that.

2024-07-12 07:53 UTC, GetPsyched commented
The design exists, it's not in the Dev Handoff page, but in the one where everything was, see the left sidebar.

For the data, just fetch from DB and then use `??` to fallback on dummy data that you can put. This way the type of the dict remains exactly what the db is providing us with. @geekysilento can give you an example if needed.

2024-08-20 11:02 UTC, heydoyouknowme0 commented on drizzle.config.ts
> +    url: "postgresql://$default:1tpVmZYrd0FG@ep-soft-limit-a1lqwhsh-pooler.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require",
why?

2024-08-20 11:03 UTC, closed without merging

2024-08-20 11:05 UTC, heydoyouknowme0 commented on drizzle.config.ts
> +    url: "postgresql://$default:1tpVmZYrd0FG@ep-soft-limit-a1lqwhsh-pooler.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require",
@KambojRajan