feat: sections-landing
nitkkr-dev/nitkkr pull request #207
Opened 2024-07-04 13:18 UTC by KambojRajan

2024-07-11 17:35 UTC, GetPsyched requested changes
Padding is a little off for the "General Administration" section. Please check.

2024-07-11 17:35 UTC, GetPsyched commented on app/[locale]/institute/sections/page.tsx
> +        heading={'h1'}
Don't use the `{}` syntax when it's just a normal string
```suggestion
        glyphDirection="dual"
        heading="h1"
```

2024-07-11 17:35 UTC, GetPsyched commented on i18n/en.ts
> +    title: 'Sections',
Make a new attribute `Sections` and put `title` in that. `Section` is reserved for the dedicated section page(s) we have.

2024-07-11 17:35 UTC, GetPsyched commented on app/[locale]/institute/sections/page.tsx
> +            const IconComponent = SectionIcons[section.urlName];
Kind of a small nit, but just `Icon` is fine
```suggestion
            const Icon = SectionIcons[section.urlName];
```

2024-07-11 17:35 UTC, GetPsyched commented on app/[locale]/institute/sections/page.tsx
> +  const SectionIcons: Record<string, IconType> = {
The convention for variable names is lower camel case
```suggestion
  const sectionIcons: Record<string, IconType> = {
```

2024-09-09 13:02 UTC, GetPsyched requested changes

2024-09-09 13:02 UTC, GetPsyched commented on server/db/schema/club-event.schema.ts
Remove this

2024-09-09 13:02 UTC, GetPsyched commented on server/db/schema/event.shema.ts
And remove this

2024-09-13 14:53 UTC, KambojRajan commented on app/[locale]/institute/sections/page.tsx
> +    accounts: MdOutlineAccountBalance,
sir this is being done by Prettier

2024-10-02 12:57 UTC, closed without merging