feature: updated slideshow according to figma
nitkkr-dev/nitkkr pull request #220
Opened 2024-09-06 12:12 UTC by geekysilento

2024-09-06 12:25 UTC, GetPsyched requested changes
Sadly, not according to Figma; following deviations:
- Icons aren't the same style (glassy/blurred bg not present)
- Icons should be slightly smaller, refer padding/size values from Figma
- Text is overflowing outside of the container

2024-09-08 07:39 UTC, heydoyouknowme0 commented
Mobile ui needs to be fixed too

2024-09-09 13:21 UTC, GetPsyched approved these changes

2024-09-09 13:22 UTC, merged

2024-09-09 13:23 UTC, GetPsyched commented on app/[locale]/page.tsx
> +          <section className="absolute bottom-0 flex flex-col space-y-4 pb-8">
```suggestion
        <address className="container absolute inset-x-0 bottom-0 hidden h-0 justify-end lg:flex">
          <ul className="absolute bottom-0 flex flex-col space-y-4 pb-8">
```