feature: events (integrated)
nitkkr-dev/nitkkr pull request #59
Opened 2024-02-01 16:58 UTC by PradeepKhatri

Fixes #30

2024-02-02 10:39 UTC, Maan2003 commented on app/events.tsx
> +        </div>
desperate need of components

2024-02-04 20:47 UTC, GetPsyched requested changes
1. Images will be fetched from Figma (later S3), remove them from the Git tree.
2. Rebase on master to get the latest stuff.
3. Use semantic HTML tags instead of `div` and `span`. Those should be your last resort.
4. Make an object for all the data, they will most likely be fetched dynamically from the database.

2024-02-14 13:50 UTC, GetPsyched requested changes

2024-02-14 13:50 UTC, GetPsyched commented on styles/globals.css
Please don't remove existing styling.

2024-02-14 13:50 UTC, GetPsyched commented on styles/globals.css
> +
We already have the fonts installed.
```suggestion
```

2024-02-14 13:50 UTC, GetPsyched commented on tailwind.config.ts
Another case of removing existing styling

2024-02-14 13:50 UTC, GetPsyched commented on tsconfig.json
> +    "env.mjs",
This had been removed. Don't add it back (happened due to bad resolution of merge conflicts during rebase)
```suggestion
```

2024-02-14 13:50 UTC, GetPsyched commented on app/[locale]/page.tsx
> +      <Events />
Don't remove the other components.
```suggestion
      <Notifications />
      <Events /> 	
      <DirectorsCorner locale={locale} />
```

2024-02-14 13:50 UTC, GetPsyched commented on components/horsesRunning.tsx
Uh, this already exists, why adding it again?

2024-02-14 13:50 UTC, GetPsyched commented on components/horsesRunning.tsx
Uh, this component already exists, why adding it again?

2024-02-14 13:50 UTC, GetPsyched commented on components/horsesRunning.tsx
Uh, this component already exists, why adding it again?

2024-02-14 13:50 UTC, GetPsyched commented on app/[locale]/events.tsx
> +      {/* -----HEADING------ */}
Remove these comments

2024-02-15 07:56 UTC, GetPsyched requested changes
Leave configuring fonts for now. We will do it globally.

2024-02-15 07:56 UTC, GetPsyched commented on app/[locale]/events.tsx
> +            <button className="mr-[8rem] text-lg font-bold lg:font-sans">
Font won't be defined based on a screen width.

2024-02-15 07:56 UTC, GetPsyched commented on app/[locale]/events.tsx
> +                className="rounded-xl border-2 bg-shades-10 px-[50px] py-[34px] font-serif text-2xl  leading-10 text-primary-20  hover:bg-shades-30 hover:text-primary-50"
No need to configure fonts

2024-02-15 07:56 UTC, GetPsyched commented on app/[locale]/events.tsx
> +                className="rounded-xl border-2 bg-shades-10 px-[56px] py-[34px] font-serif text-2xl leading-10 text-primary-20 hover:bg-shades-30 hover:text-primary-50"
Same here

2024-02-15 09:11 UTC, GetPsyched commented on tsconfig.json
> +    ".next/types/**/*.ts",
Remove the comma here so that it goes back to a single line.

2024-02-15 09:11 UTC, GetPsyched commented on tsconfig.tsbuildinfo
Remove this file from the Git tree. It's not supposed to be pushed

2024-02-17 15:53 UTC, GetPsyched commented on tailwind.config.ts
Please don't edit global styles.

2024-02-18 12:27 UTC, GetPsyched requested changes

2024-02-18 12:27 UTC, GetPsyched commented on app/[locale]/events.tsx
> +
Remove if redundant

2024-02-18 12:27 UTC, GetPsyched commented on app/[locale]/events.tsx
> +            paddingBottom: '6pc',
What is `pc`? Is this a typo? Even if not, use standard units.

2024-02-18 12:27 UTC, GetPsyched commented on app/[locale]/events.tsx
> +                    <p className="">
```suggestion
                    <p>
```

2024-02-18 12:27 UTC, GetPsyched commented on app/[locale]/events.tsx
> +                        <a href={ad.link}>{ad.title}</a>
Please use `<Link />` from `next/link` instead of `a` tags.

2024-02-18 12:27 UTC, GetPsyched commented on app/[locale]/events.tsx
> +                    </figure>
There's no point wrapping inside a tag if there's only one child.

2024-09-09 11:52 UTC, GetPsyched commented
Addressed by #221

2024-09-09 11:52 UTC, closed without merging