feature: initialized shadcn and added input generics
nitkkr-dev/nitkkr pull request #68
Opened 2024-02-07 10:30 UTC by geekysilento

2024-02-07 10:32 UTC, geekysilento commented
no more crlf BS, only clean source code.

2024-02-07 10:37 UTC, GetPsyched commented
Awesome

2024-02-07 11:07 UTC, GetPsyched requested changes
There's so much to review :(

Please finish this off from your end along with polishing and then I can review and merge quickly

2024-02-07 11:36 UTC, geekysilento commented on components.json
this is a file used to initialize shadcn, in here u can modify things like the default theme shadcn uses, where its components will be installed to, etc

2024-02-07 18:36 UTC, geekysilento commented
@GetPsyched how should i handle Single and Multi Select (with custom data set in drop down)? How will we populate the dropdown list? will it be defined when calling the element like <DropDown items = {itemList} /> ? and the array itemList will be handled by the form builder?

also confused about date-time plus its usecare? i have a date input generic and a time input generic, why do we need a separate single generic?

Third thing, fetching countryCodes for the telephone input generic, I still think its overkill fetching from a external source(currently idk where to fetch it from, as the site you used doesnt expose JUST the dialing codes in a specific route), my current implementation of an array of dialing codes, imo is fine. Opinions?

2024-02-08 19:53 UTC, GetPsyched commented
> also confused about date-time plus its usecare? i have a date input generic and a time input generic, why do we need a separate single generic?

Some inputs would be only dates and some only times. For example, an all-day event would just have date, a lecture would just have time, but an exam would have both.

> Third thing, fetching countryCodes for the telephone input generic, I still think its overkill fetching from a external source(currently idk where to fetch it from, as the site you used doesnt expose JUST the dialing codes in a specific route), my current implementation of an array of dialing codes, imo is fine. Opinions?

It is fine, let's leave this for later.

2024-02-17 06:57 UTC, GetPsyched commented
Can you give a summary of what has changed?

2024-03-16 17:16 UTC, closed without merging

2024-03-17 13:58 UTC, GetPsyched commented
Closed in favour of #102