Global search
nitkkr-dev/nitkkr pull request #74
Opened 2024-02-09 12:08 UTC by legitk8

2024-02-15 10:45 UTC, maan2003 commented on .gitignore
> +typesense-data/
use your local git config `~/.config/git/ignore` globally or `.git/info/exclude` in repo

2024-02-26 17:28 UTC, GetPsyched requested changes
Rebase on master

2024-02-27 18:21 UTC, GetPsyched requested changes

2024-02-27 18:21 UTC, GetPsyched commented on .gitignore
> +# Next.js build output
Why is this in the diff?

2024-02-27 18:21 UTC, GetPsyched commented on search/search.ts
> +const query = 'arya'
Separate imports and declarations

2024-03-21 17:14 UTC, GetPsyched requested changes

2024-03-21 17:14 UTC, GetPsyched commented on .gitignore
> +# Next.js build output
@legitk8 not resolved^

2024-03-21 17:14 UTC, GetPsyched commented on search/search.ts
> +const query = 'arya'
same here

2024-04-24 23:27 UTC, GetPsyched requested changes

2024-04-24 23:27 UTC, GetPsyched commented on server/typesense/schema.ts
> +  // default_sorting_field: 'name',
Why is this commented out?

2024-04-24 23:27 UTC, GetPsyched commented on server/typesense/schema.ts
> +    { name: 'image', type: 'image', index: false },
um no? it will be a URL which is a string.

2024-04-24 23:27 UTC, GetPsyched commented on server/typesense/init.ts
> +// });
Why leave this in?

2024-04-24 23:27 UTC, GetPsyched commented on app/api/typesense-init/route.ts
> +import { resolve } from "path";
Unused import

2024-04-29 03:11 UTC, GetPsyched commented
Done in #172

2024-04-29 03:11 UTC, closed without merging